--liquibase formatted sql

--changeset vadim:1
--comment: Create users table with name, password, date of birth
CREATE TABLE IF NOT EXISTS users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(500) NOT NULL,
    password       VARCHAR(500) NOT NULL,
    date_of_birth  DATE
);
--rollback: DROP TABLE users;

--changeset vadim:2
--comment: Add table and column comments for users
COMMENT ON TABLE users IS 'Stores basic user information';
COMMENT ON COLUMN users.id IS 'Primary key';
COMMENT ON COLUMN users.name IS 'Full name of the user';
COMMENT ON COLUMN users.password IS 'Hashed user password';
COMMENT ON COLUMN users.date_of_birth IS 'User date of birth in format: 01.05.1993';

--changeset vadim:3
--comment: Create accounts table
CREATE TABLE IF NOT EXISTS accounts
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance  DECIMAL,
    user_id  BIGINT NOT NULL UNIQUE REFERENCES users(id)
);
--rollback: DROP TABLE accounts;

--changeset vadim:4
--comment: Add table and column comments for accounts
COMMENT ON TABLE accounts IS 'Stores user account balances';
COMMENT ON COLUMN accounts.id IS 'Primary key';
COMMENT ON COLUMN accounts.balance IS 'Account balance in rubles and kopecks';
COMMENT ON COLUMN accounts.user_id IS 'Foreign key to users table, one-to-one';

--changeset vadim:5
--comment: Create email_data table
CREATE TABLE IF NOT EXISTS email_data
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email   VARCHAR(200) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id)
);
--rollback: DROP TABLE email_data;

--changeset vadim:6
--comment: Add table and column comments for email_data
COMMENT ON TABLE email_data IS 'Stores user emails';
COMMENT ON COLUMN email_data.id IS 'Primary key';
COMMENT ON COLUMN email_data.email IS 'User email address (unique)';
COMMENT ON COLUMN email_data.user_id IS 'Foreign key to users table';

--changeset vadim:7
--comment: Create phone_data table
CREATE TABLE IF NOT EXISTS phone_data
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone   VARCHAR(13) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id)
);
--rollback: DROP TABLE phone_data;

--changeset vadim:8
--comment: Add table and column comments for phone_data
COMMENT ON TABLE phone_data IS 'Stores user phone numbers';
COMMENT ON COLUMN phone_data.id IS 'Primary key';
COMMENT ON COLUMN phone_data.phone IS 'User phone in format 79207865432';
COMMENT ON COLUMN phone_data.user_id IS 'Foreign key to users table';
